# -*- coding: utf-8 -*-
"""Aula01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ryz7VuZqECbP7r7yiK9Z0EBeF8jNE3Ze

# Introdução à lógica de programação {

Aula 1 - variáveis, operadores, print, input,
operadores lógicos, relacionais
[usando Python]

Coletivo Mirtha Lina

# }

# Lógica de programação {

Modo como se escreve um programa, um algoritmo

# }

# Algoritmo {

Sequência de passos para realizar uma tarefa ou resolver um problema

# }

# Variáveis
As variáveis armazenam dados, valores que podem ser alterados ao longo do código ou podem ser constantes. Algotítmos são formados por variáveis
"""

#Exemplo
g1 = 'pera'
g2 = 'maça'
g3 = 'banana'
g4 = 'morango'

print(g1, g2, g3, g4)

"""#Tipos de variáveis

Números inteiros: Inteiro → Int

Números decimais: Real → float

Letras ou palavras: Caracteres → Str

Valores Lógicos: Booleano → Bool

Listas: Listas → List

Não precisamos dizer para o Python qual é o tipo da variável que estamos criando. Ele entende tudo sozinho.
"""

x = 10 ##int ou inteiro
y = 1.455 ##decimal ou float
nome = 'Melissa' ###caracter ou str (string)
logico = 'True' ###operador lógico ou bool (booleano)

print(x, y, nome, logico)

"""# Regras de nomeação de variáveis

- Ser formada por um ou mais caracteres;

- Primeiro caracter deve ser sempre uma letra;

- Não é permitido símbolos ( / ^& % $....)
Podemos usar o sinal _ (underline)

Pode: A, idade2, SOMA_NOTAS, MediaNotas, endereco
Não pode: 239, 6idade, A&B, soma-notas, (parenteses)
"""

nome22 = 'Melissa'

type(nome22) ##O comando type diz qual o tipo da variável usada.

##Crie uma variável de cada tipo
faculdade = 'UFABC'
idade = 18
valor = 55.7
prosseguir = True
dias = ['sabado', 'segunda', 'terca']

print(faculdade)
print(idade)
print(valor)
print(prosseguir)
print(dias)

print('Olá mundo!')

print('12+1')
print(12+1)

nome = 'Melissa'
idade = 18
print(f'Olá, {nome}! Você tem {idade} anos.')

nome = 'Melissa'
sobrenome = 'Oliveira'
print (nome + " " + sobrenome)

a = 6 + 1
b = 15/3
c = b * 5
d = a%3 ##a % mostra o resto da divisão
g = 'a' + 'b' + 'c'
h = 'Olá ' + 'mundo!'
print(a)
print(b)
print(c)
print(d)
print(g)
print(h)

nome = input('Digite o seu nome: ')
idade = input('Digite a sua idade: ')
print(nome)
print(idade)

n1 = int(input('Digite um número: '))
n2 = int(input('Digite mais um número: '))
soma = n1 + n2
print(soma)

"""O input automaticamente
recebe strings, a não ser
que a gente diga para ele
que tipo de dado vamos
receber.
"""

##Conversão de texto para número
idade_string = '18'
idade_numero = int(idade_string)
print(type(idade_string),idade_string)
print(type(idade_numero),idade_numero)

##Exercício: Solicita o ano de nascimento do usuário e o ano atual, e calcula qual a idade aproximada do usuário
anoatual = int(input('Digite o ano atual: '))
anonascimento = int(input('Digite o ano que você nasceu: '))
idade = anoatual - anonascimento
print(f'Você tem aproximadamente {idade} anos.')

##Conversão de número para texto
nota = 9.5
frase = 'Minha nota foi '
frase_completa = frase + str(nota)
print(frase_completa)

"""# Falando um pouco de matemática...
# Operadores aritméticos

##OPERADOR -> OPERAÇÃO
### + Adição
### - Subtração
### * Multiplicação
### / Divisão
### ** Potenciação
### % Módulo
"""

##Exercício: Média
#Descrição   : Solicita 3 números para o usuário e faz a média deles.

num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite o segundo número: '))
num3 = float(input('Digite o terceiro número: '))
media = (num1 + num2 + num3) / 3
print(f'A média dos três números informados é: {media}.')

##Exercício: Área do quadrado
#Descrição   : Calcular a área de um quadrado

lado = float(input('Informe o lado do quadrado: '))
area = (lado * lado)
print(f'A área do quadrado é: {area}.')

##Exercício: Área e perímetro de um retângulo
#Esse programa solicita a base e a altura de um retângulo e calcula sua área e perímetro.

base = float(input('Informe o valor da base do retângulo: '))
altura = float(input('Agora informe o valor da altura do retângulo: '))
area = (base * altura)
perimetro = (base * 2) + (altura * 2)
print(f'A área do retângulo é: {area}.')
print(f'O perímetro do retângulo é: {perimetro}.')

##Exercício: Aumento do valor de um produto
#Esse programa solicita o nome e o valor de custo de um produto qualquer, e então calcula um aumento de 65% e informa qual será o valor da venda.
nome_produto = input('Informe o nome do produto: ')
preco_produto = float(input('Informe o preço do produto: '))

preco_final = preco_produto + 0.65 * preco_produto ##pesquisar melhor depois sobre esse cálculo

print(f'Você pode vender o produto informado por: R${preco_final}')

emprestimo = float(input("Qual o valor de empréstimo que você quer? "))
meses = int(input("Deseja pagar em quantos meses? "))
taxa = 0.02  # Taxa fixa de juros de 2% ao mês (pode ser alterada)

resultado = emprestimo * (1 + taxa) ** meses

# Saída formatada
print(f"Ao final de {meses} meses, você pagará: R${resultado:.2f} de juros compostos!")

"""#Operadores relacionais

Igual: ==

Diferente: !=

Maior: >

Menor: <

Menor ou igual: <=

Maior ou igual: >=
"""

##Comparações
print(1 == 1)
print(1 != 2)
print(4 < 3)
print(6 > 4)
print(1 <= 1)
print(0.5 >= 1)

##Comparações numéricas
print(100==20)
print(100>20)
print(100<20)
print(40>=40)
print(20<=100)
print(40!=40)

"""##Prioridade entre os operadores

1° Operadores aritméticos

2° Relacionais

3° não

4° e

5° ou

6° xou

##Operadores lógico
AND ou E: Uma sentença é verdadeira se e somente se todos os termos forem verdadeiros

OR ou OU: Uma sentença resulta verdadeira se qualquer um dos termos forem verdadeiros

NOT ou NÃO: Este operador inverte um termo

XOR ou XOU: Ou exclusivo - Se as duas forem diferentes, a sentença é verdadeira

##Operador E
Verdadeiro e Verdadeiro = Verdadeiro

Verdadeiro e Falso = Falso

Falso e Verdadeiro = Falso

Falso e Falso = Falso

##Operador OU

Verdadeiro e Verdadeiro = Verdadeiro

Verdadeiro e Falso = Verdadeiro

Falso e Verdadeiro = Verdadeiro

Falso e Falso = Falso

##Operador XOU

Verdadeiro e Verdadeiro = Falso

Verdadeiro e Falso = Verdadeiro

Falso e Verdadeiro = Verdadeiro

Falso e Falso = Falso

##Operador NÃO
 Verdadeiro = Falso

 Falso = Verdadeiro
"""

#Exemplo E
g1 = 'predio'
g2 = 'casa'
g3 = 'policia'
g4 = 'casa'

print("O valor de g1 é : " + g1)
print("O valor de g2 é : " + g2)
print("O valor de g3 é : " + g3)
print("O valor de g4 é : " + g4)

print ("Quero saber se g1 é igual a g3 e g3 é igual a g4")

print (g1 == g3 and g3 == g4) ##falso e falso

print("g1 é igual a g3 ? " + str(g1 == g3))
print("g3 é igual a g4 ? " + str(g3 == g4))
print("g2 é igual a g4 ? " + str(g2 == g4))

#Exemplo OU
g1 = "predio"
g2 = "casa"
g3 = "policia"
g4 = "casa"

print("O valor de g1 é : " + g1)
print("O valor de g2 é : " + g2)
print("O valor de g3 é : " + g3)
print("O valor de g4 é : " + g4)

print ("Quero saber se g1 é igual a g3 ou g2 é igual a g4")
print (g1 == g3 or g2 == g4) #falso ou verdadeiro

print("g1 é igual a g3 ? " + str(g1 == g3))
print("g2 é igual a g4 ? " + str(g2 == g4))

#Vamos praticar
#1 - Crie um programa que solicite a usuária quedigite um número qualquer e guarde este número em uma variável
#2 - Em seguida, verifique se este número está no intervalo entre 10 e 20 (10<=numero<=20). Escreva na tela o resultado.
num = int(input('Digite um número inteiro qualquer: '))

##print(10 <= num <=20) -> aqui esstá verificando se o número informado é maior ou igual que 10 e menor ou igual que 20

print("O número informado está entre 10 e 20? " + str(10 <= num <= 20))